CREATE TABLE users(

    id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    balance NUMERIC(15,2),
    dateCreation TIMESTAMP DEFAULT CURRENT_TIMESTAMP

)